/*
 * dh.h -- Diffie-Hellman over RFC 3526 Group 14
 */

#ifndef DH_H
#define DH_H

#include <openssl/bn.h>

#include <cstddef>
#include <string>

namespace dh {

/* 2048-bit values are always serialised to exactly this many bytes. */
constexpr size_t PUB_BYTES = 256;

/* Private exponent size. RFC 3526 rates group 14 at 110-160 bits of
   security with a matching exponent size of 220-320 bits, so 320 covers the
   upper end. A full 2048-bit exponent would cost 6x the work for nothing,
   since the discrete log is no harder than the subgroup order anyway. */
constexpr int PRIV_EXP_BITS = 320;

// modular exponentiation: out = base^exp mod m
bool my_mod_exp(BIGNUM *out, const BIGNUM *base, const BIGNUM *exp,
                const BIGNUM *m, BN_CTX *ctx);

// group parameters: p, g, and q = (p-1)/2
class Group {
public:
    Group();
    ~Group();

    Group(const Group &) = delete;
    Group &operator=(const Group &) = delete;

    bool ok() const { return ok_; }

    const BIGNUM *p() const { return p_; }
    const BIGNUM *g() const { return g_; }
    const BIGNUM *q() const { return q_; }

    /* Confirms p is prime and (p-1)/2 is prime too. Slow (about a second),
       so it's only called from dh_test, never on the connection path. */
    bool verify_safe_prime(BN_CTX *ctx) const;

private:
    BIGNUM *p_;
    BIGNUM *g_;
    BIGNUM *q_;
    bool ok_;
};

// validating a public value that arrived over the network

/* 1 < y < p-1. Rejects 0, 1 and p-1, which force the shared secret to a
   known value or to one guessable bit. */
bool in_range(const BIGNUM *y, const Group &grp);

/* y^q mod p == 1, i.e. y lies in the order-q subgroup generated by g = 2.
   Rejects non-residues, which would leak one bit of our private exponent
   per handshake. Costs one full-size exponentiation via my_mod_exp. */
bool in_subgroup(const BIGNUM *y, const Group &grp, BN_CTX *ctx);

// one side of one exchange -- owns the private exponent and wipes it
class KeyPair {
public:
    explicit KeyPair(const Group &grp);
    ~KeyPair();

    KeyPair(const KeyPair &) = delete;
    KeyPair &operator=(const KeyPair &) = delete;

    /* Pick a fresh private exponent and compute A = g^a mod p. */
    bool generate(BN_CTX *ctx);

    /* Serialise A to exactly PUB_BYTES bytes, big-endian, zero-padded. */
    bool public_bytes(unsigned char out[PUB_BYTES]) const;

    /* Validate the peer value, then compute Z = peer^a mod p and serialise
       it to exactly PUB_BYTES bytes. Returns false (with a reason in *why)
       if the peer value fails any validation check. */
    bool compute_shared(const unsigned char peer[PUB_BYTES],
                        unsigned char out[PUB_BYTES],
                        BN_CTX *ctx,
                        std::string *why) const;

private:
    const Group &grp_;
    BIGNUM *priv_;
    BIGNUM *pub_;
};

// the exchange itself, over an already-connected socket

/*
 * Runs one complete DH exchange on fd and returns the raw shared secret,
 * serialised to a fixed PUB_BYTES bytes.
 *
 * Symmetric: both sides send their own public value first, then read the
 * peer's. 256 bytes fits easily in the socket buffers so there's no
 * deadlock, and it saves a round trip.
 *
 * Wire format: [4-byte big-endian length = 256][256-byte value]
 *
 * The caller must hash the result before using it as a key, and must wipe
 * it (OPENSSL_cleanse) once the key is derived.
 */
bool run_handshake(int fd, unsigned char shared_out[PUB_BYTES],
                   std::string *why);

}  /* namespace dh */

#endif /* DH_H */
